### ISSUE TITLE
loading .json files fails

### ISSUE THREAD

**Issue by adriatic** [aurelia-ui-toolkits/aurelia-kendoui-bundles#1]
### Examples: 
1. Area charts: binding to remote data -- https://gist.run/?id=a54029487bb2c93310cc818dfdffc988
2. Area charts: binding to grouped data --  https://gist.run/?id=247d14476242e4e71c04784db4670cae
3. Area charts: binding to local data -- https://gist.run/?id=17d2fc456b35a54c0ca5287465e1bf53
4.  Area charts: logarithmic axis -- https://gist.run/?id=69301cf79e16e6d5ffbf45f690df3e2b

As this is likely a problem with the 'json loader' in the current bundle, I did not want to continue adding support to the catalog app for running gists until this gets resolved

**Comment by JeroenVinke** [comment]
this was fixed
